services:
    - type: web
      name: aladin-chat-server
      env: node
      buildCommand: npm install
      startCommand: node server.js
      envVars:
          - key: NODE_ENV
            value: production
